server:
  port: 8999


eureka:
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: lb://customer-service
        predicates:
          - Path=/cc/**
       

          
        
          
    
